FROM node:22-alpine
WORKDIR /app

RUN apk add --no-cache python3 make g++

COPY package.json yarn.lock tsconfig.json tsconfig.build.json nest-cli.json ./
RUN yarn install

COPY apps/ apps/
COPY libs/ libs/

CMD ["yarn", "start"]
