FROM node:22-alpine
WORKDIR /app/apps/frontend-cms

COPY apps/frontend-cms/package.json apps/frontend-cms/package-lock.json* apps/frontend-cms/yarn.lock* ./
RUN yarn install || npm install

COPY apps/frontend-cms ./

CMD ["yarn", "dev", "--host", "0.0.0.0"]
