worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Resolver for dynamic Docker container DNS resolution
    resolver 127.0.0.11 valid=10s ipv6=off;

    server {
        listen 80;
        server_name ~^(?<client>[^.]+)\.api\..+$ ~^(?<client>[^.]+)\.ahha-be\.local$ api.adityahadi.my.id localhost 127.0.0.1 "";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location /admin {
            proxy_pass http://admin:9002;
        }

        location /loyalty-admin {
            proxy_pass http://loyalty-admin:9003;
        }

        location /user-admin {
            proxy_pass http://user-admin:9004;
        }

        location /loyalty {
            proxy_pass http://loyalty-consumer:9005;
        }

        location /user {
            proxy_pass http://user-consumer:9006;
        }

        location /product-admin {
            proxy_pass http://product-admin:9007;
        }

        location /product {
            proxy_pass http://product-consumer:9008;
        }

        location /products {
            proxy_pass http://product-consumer:9008;
        }

        location /redistro {
            proxy_pass http://redistro:9009;
        }

        # Global CORS Handling
        if ($request_method = OPTIONS) {
            add_header 'Access-Control-Allow-Origin' '$http_origin' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, DELETE, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,x-api-key,x-tenant-override,x-subdomain' always;
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        }

        add_header 'Access-Control-Allow-Origin' '$http_origin' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, DELETE, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,x-api-key,x-tenant-override,x-subdomain' always;
    }
}
