worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
            listen 80;
            server_name ~^(?<client>[^.]+)\.ahha-be\.local$;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            location /admin {
                proxy_pass http://localhost:9002;
            }
            location /user-admin {
                proxy_pass http://localhost:9004;
            }
            location /user {
                proxy_pass http://localhost:9006;
            }
            location /loyalty-admin {
                proxy_pass http://localhost:9003;
            }
            location /loyalty {
                proxy_pass http://localhost:9005;
            }

            if ($request_method = OPTIONS) {
                return 204;
            }

            # Tambahkan CORS headers jika perlu
            add_header 'Access-Control-Allow-Origin' * always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, DELETE, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' * always;
        }
}
